#!/usr/bin/env perl
use warnings;
use strict;
use v5.10.0;

use lib "$ENV{HOME}/git/dse.d/printable-paper/lib";
use My::Printable::Paper::Maker;

our $opt_verbose = 0;
our $opt_dry_run = 0;
our $opt_force   = 0;

Getopt::Long::Configure('bundling', 'gnu_compat', 'no_ignore_case');
Getopt::Long::GetOptions(
    'v|verbose+' => \$opt_verbose,
    'n|dry-run'  => \$opt_dry_run,
    'f|force'    => \$opt_force,
    'quiet'      => sub {
        if ($opt_verbose < 0) {
            $opt_verbose -= 1;
        } else {
            $opt_verbose = -1;
        }
    },
    'h|help' => sub { usage(); exit 0; },
) or die("Type '$0 --help' for help.\n");

sub usage { print <<END; }
usage: $0 [<option> ...] [<keyword> ...]
options:
  -h, --help
  -v, --verbose
  -n, --dry-run
  -f, --force
END

my $maker = My::Printable::Paper::Maker->new();
$maker->verbose($opt_verbose);
$maker->dryRun($opt_dry_run);
$maker->force($opt_force);
$maker->run(@ARGV);
