#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

printable="${HOME}/git/dse.d/printable-paper/bin/printable-paper"

printable () {
    command "${printable}" "$@"
}

rm -frv examples || true
mkdir -p examples

#         Paper Size*   Ruling       Filename base               Options
#         ------------- ---------    --------------------------- --------------------------------------------------------------------
printable               seyes     -o examples/seyes              --pdf        --dpi 600 --lw 2 --fw 1
printable --half-letter seyes     -o examples/seyes3-half-letter --pdf --2p2u --dpi 600 --lw 4 --fw 2 -Dunit=1/4in -Ddividing-lines=3
printable               quadrille -o examples/quadrille          --pdf        --dpi 600 --lw 2 --fw 1
printable               quadrille -o examples/quadrille10        --pdf        --dpi 600 --lw 2 --fw 1 -Dunit=1/10in

# * size of a SINGLE page.
