#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

printable="${HOME}/git/dse.d/printable-paper/bin/printable-paper"

printable () {
    command "${printable}" --verbose "$@"
}

rm -frv dses-examples || true
mkdir -p dses-examples
cd dses-examples

#                  Paper Size       Ruling       Filename base                    Options
#                  ---------------- ---------    -------------------------------- ---------------------------------------------------------------------------------------------
p1  () { printable --letter         seyes     -o seyes3-letter                    --pdf        --dpi 600         --lw 4 --fw 2 -Dunit=1/4in    -Dfeint-lines=3                      ; }
p2  () { printable --half-letter    seyes     -o seyes3-half-letter               --pdf --2p2u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in    -Dfeint-lines=3                      ; }
p3  () { printable --letter         quadrille -o quadrille4-feint3-letter         --pdf --2p   --dpi 600         --lw 4 --fw 2 -Dunit=1/4in    -Dfeint-lines=3 -Dmargin-line=yes    ; }
p4  () { printable --half-letter    quadrille -o quadrille4-feint3-half-letter    --pdf --2p2u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in    -Dfeint-lines=3 -Dmargin-line=yes    ; }
p5  () { printable --quarter-letter quadrille -o quadrille4-feint3-quarter-letter --pdf --2p4u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in    -Dfeint-lines=3 -Dmargin-line=0.5in  ; }
p6  () { printable --letter         quadrille -o quadrille4-major4-letter         --pdf        --dpi 600 --mjw 4 --lw 2        -Dunit=1/4in    -Dmajor-lines=4                      ; }
p7  () { printable --letter         quadrille -o quadrille10-letter               --pdf        --dpi 600 --mjw 8 --lw 4 --fw 2 -Dunit=1/2in    -Dmajor-lines=2 -Dfeint-lines=5      ; }
p8  () { printable --letter         quadrille -o quadrille1064-letter             --pdf        --dpi 600 --mjw 6 --lw 2        -Dunit=10/192in -Dmajor-lines=3 -Dmajor-lines-y=8    ; }

all () { p1; p2; p3; p4; p5; p6; p7; p8; }

if (( $# )) ; then
    for i ; do
	"$i"
    done
else
    all
fi

# Local Variables
# indent-tabs-mode: nil
# End
