#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

printable="${HOME}/git/dse.d/printable-paper/bin/printable-paper"

printable () {
    command "${printable}" --verbose "$@"
}

dir=examples

rm -frv "${dir}" || true
mkdir -p "${dir}"

#                   Paper Size        Ruling        Filename base                                             Options
#                   ----------------  ---------     --------------------------------------------------------  ---------------------------------------------------------
p1  () { printable  --letter          seyes      -o "${dir}"/seyes--quarter-inch-3-feints--letter             --pdf --2p   --dpi 600         --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=3                                                  ; }
p2  () { printable  --half-letter     seyes      -o "${dir}"/seyes--quarter-inch-3-feints--half-letter        --pdf --2p2u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=3                                                  ; }

p3  () { printable  --letter          quadrille  -o "${dir}"/quadrille--quarter-inch-3-feints--letter         --pdf --2p   --dpi 600         --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=3 -Dleft-margin-line=yes                           ; }
p4  () { printable  --half-letter     quadrille  -o "${dir}"/quadrille--quarter-inch-3-feints--half-letter    --pdf --2p2u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=3 -Dleft-margin-line=3/4in -Dtop-margin-line=3/4in ; }
p5  () { printable  --quarter-letter  quadrille  -o "${dir}"/quadrille--quarter-inch-3-feints--quarter-letter --pdf --2p4u --dpi 600         --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=3 -Dleft-margin-line=1/2in                         ; }

p6  () { printable  --letter          quadrille  -o "${dir}"/quadrille--quarter-inch--letter                  --pdf --2p   --dpi 600 --mjw 4 --lw 2        -Dunit=1/4in -Dmajor-lines=4                                                  ; }

p7  () { printable  --letter          quadrille  -o "${dir}"/quadrille--half-inch-5-feints--letter            --pdf --2p   --dpi 600 --mjw 8 --lw 4 --fw 2 -Dunit=1/2in -Dmajor-lines=2 -Dfeint-lines=5                                  ; }
p8  () { printable  --letter          quadrille  -o "${dir}"/quadrille--third-inch-4-feints--letter           --pdf --2p   --dpi 600 --mjw 8 --lw 4 --fw 2 -Dunit=1/3in -Dfeint-lines=4 -Dmajor-lines=4                                  ; }
p9  () { printable  --letter          quadrille  -o "${dir}"/quadrille--quarter-inch-4-feints--letter         --pdf --2p   --dpi 600 --mjw 8 --lw 4 --fw 2 -Dunit=1/4in -Dfeint-lines=4 -Dmajor-lines=4                                  ; }

p10 () { printable  --letter          quadrille  -o "${dir}"/quadrille--quarter-inch-dashed--letter           --pdf --2p   --dpi 600 --mjw 4 --lw 2        -Dunit=1/4in -Dmajor-lines=4 -Ddashed=4; }
p11 () { printable  --letter          quadrille  -o "${dir}"/quadrille--quarter-inch-dotted--letter           --pdf --2p   --dpi 600 --mjw 4 --lw 2 --dw 8 -Dunit=1/4in -Dmajor-lines=4 -Ddotted=4; }

p12 () {
    printable quadrille \
              --letter \
              -o "${dir}"/quadrille--quarter-inch-3-feints-dotted--half-letter \
              --pdf --2p2u \
              --dpi 600 \
              --major-line-width=8 \
              --regular-line-width=4 \
              --feint-line-width=2 \
              --major-dot-width=16 \
              --regular-dot-width=8 \
              --feint-dot-width=4 \
              -Dunit=1/4in \
              -Dmajor-lines=4 \
              -Dfeint-lines=3 \
              -Dleft-margin-line=3/4in \
              -Dtop-margin-line=3/4in  \
              -Dmajor-dashed=8 \
              -Ddashed=4 \
              -Dfeint-dashed=2
}

p13 () {
    printable embry1 \
              --half-letter \
              -o "${dir}"/embry1--half-letter \
              --pdf --2p2u --2p \
              --dpi 600 \
              --major-line-width=4 \
              --regular-line-width=2 \
              --feint-line-width=2 \
              --major-dot-width=32 \
              --regular-dot-width=16 \
              --feint-dot-width=8 \
              -Dunit=1/4in \
              -Dleft-margin-line=3/4in \
              -Dtop-margin-line=3/4in \
              -Dvertical-feint-dashed=2 \
              --disable-developer-mark
}

all () { p1; p2; p3; p4; p5; p6; p7; p8; p9; p10; p11; p12; p13; }

if (( $# )) ; then
    for i ; do
	"$i"
    done
else
    all
fi

# Local Variables
# indent-tabs-mode: nil
# End
